package questoes;

public class Q4 {
	/*
		o bloco try-catch funciona em dois passos, contando com um passo extra opcional (finally).
		
		O primeiro passo é verificar se uma sequencia de acoes foi feita com sucesso.
		Caso não tenha sido, o bloco try cria uma excção e passa para o catch.
		
		O catch só é executado quando a operação do try falha. Nele podemos por exemplo 
		finalizar a função de onde ele está (já que o código iria dar erro) e/ou escrever
		a mensagem de erro presente no exception.
		
		O bloco final (e opcional), finally, sempre será executado, independente de houve 
		uma exceção ou não
		
		Esse bloco é importante pois permite que nós possamos checar certas "etapas de risco"
		do nosso código, impedindo que o programa quebre seu fluxo
	*/
}
